services:
  - type: web
    name: gbpusd-forex-app
    runtime: python
    pythonVersion: "3.9.16"
    buildCommand: |
      python -m pip install --upgrade pip==21.3.1
      pip install setuptools==59.8.0 wheel==0.37.1
      pip install numpy==1.21.6 --no-binary numpy
      pip install -r requirements.txt
    startCommand: gunicorn app:app