services:
  - type: web
    name: gbpusd-forex-app
    runtime: python
    pythonVersion: "3.10.11"
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt --no-cache-dir
    startCommand: gunicorn app:app